### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by tshemsedinov** [erotourtes/SnakeJS#1]
1. Just a hint: I'd propose to use MIT license as most common, known, and permissive
2. Very short file to exist: https://github.com/erotourtes/SnakeJS/blob/main/src/main.js
I'd prefer to have:
```js
import Game from "./core/game.js";

const game = new Game();
game.start();
```
3. Hardcoded magic numbers: https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/game.js#L116 and https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/game.js#L125 and https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/game.js#L128 and https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/game.js#L132 and https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/game.js#L142 and other places
4. You use class `Game` as a scope not as a model of `Game`, it should be decomposed: https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/game.js#L12
5. Terrible collection of antipatterns: pretty columns and hardcoded magic numbers, cryptic code (not clear meaning, can be fixed with intermediate variables with proper naming): https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/effects.js#L54-L63
6. Do not use ternary for branching, we have ternary for expressions to be assigned to variable or passed somewhere: https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/handlers/keyPressedHandlerMobile.js#L18-L19
7. I suppose `from` not `form` :smiley: https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/core/physics/vector.js#L25
8. You can put `this.events[eventName]` to intermediate variable https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/utils/eventEmitter.js#L11-L13
9. It's better to use `npm` and `package.json` to define dependencies like this crappy code library (I'd not recommend it at all): https://github.com/erotourtes/SnakeJS/blob/main/src/dependencies/pixi.mjs
10. I'd prefer to have collection of allowed event names and a single `on(name, cb)` method, not copy/paste code: https://github.com/erotourtes/SnakeJS/blob/63bf8a4d933844a26d73a5d25705e25ed82c0fa6/src/snake/snake.js#L68-L82

**Comment by erotourtes** [comment]
Hi, thanks for your feedback, I appreciate it. I've fixed everything except the 9th point (I tried but faced weird issues with hosting, so I will move to npm packages when I know it better).

The decomposition of the class really helped. Now I see, that I can implement everything without an event emitter, which should be a much better option.
